# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "afd profile delete",
)
class Delete(AAZCommand):
    """Delete an existing  Azure Front Door Standard or Azure Front Door Premium or CDN profile with the specified parameters. Deleting a profile will result in the deletion of all of the sub-resources including endpoints, origins and custom domains.

    :example: Delete an AFD profile.
        az profile delete -g group --profile-name profile
    """

    _aaz_info = {
        "version": "2024-09-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.cdn/profiles/{}", "2024-09-01"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, None)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.profile_name = AAZStrArg(
            options=["-n", "--name", "--profile-name"],
            help="Name of the Azure Front Door Standard or Azure Front Door Premium or CDN profile which is unique within the resource group.",
            required=True,
            id_part="name",
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        
        _args_schema.with_policy_token = AAZBoolArg(
            options=["--with-policy-token"],
            help="Indicates that a policy token should be acquired and included before deleting the AFD profile."
        )

        _args_schema.policy_token = AAZStrArg(
            nullable=True
        )

        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.ProfilesDelete(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        if self.ctx.args.with_policy_token:
            response = self.AcquirePolicyToken(ctx=self.ctx)()
            token = response.get("token")
            print("Successfully received token, passing into header for profile delete")

    @register_callback
    def post_operations(self):
        pass

    class ProfilesDelete(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [204]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_204,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/acquirePolicyToken",
                **self.url_parameters
            )

        @property
        def method(self):
            return "DELETE"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-09-01",
                    required=True,
                ),
            }
            return parameters
        
        @property
        def content(self):
            operation_uri = {
                f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}"
                f"/resourceGroups/{self.ctx.args.resource_group}/providers/Microsoft.Cdn.profiles/{self.ctx.args.profile_name}"
                "?api-version=2025-04-15"
            }

            return {
                "operation": {
                    "uri": operation_uri,
                    "httpMethod": "DELETE"
                }
            }

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "x-ms-policy-external-evaluations", self.ctx.policy_token if self.ctx.args.with_policy_tok else {},
                ),
            }
            return parameters
        
        def on_200(self, session):
            pass

        def on_204(self, session):
            pass
    
    class AcquirePolicyToken(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"
        
        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)
            
            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cdn/profiles/{profileName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "profileName", self.ctx.args.profile_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-03-01",
                    required=True,
                ),
            }
            return parameters
        
        @property
        def header_parameters(self):
            if not self.ctx.args.with_policy_token:
                return {}
            
            parameters = {
                **self.serialize_header_param(
                    "x-ms-policy-external-evaluations", self.ctx.args.policy_token
                ),
            }
            return parameters

        def on_200(self, session):
            pass

        def on_204(self, session):
            pass
    
    class AcquirePolicyToken(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"
        
        def __call__(self, *args, **kwargs):
            print("Making request...")
            request = self.make_request()
            print(f"Request made with URL: {request.url} and Method: {self.method}")
            session = self.client.send_request(request=request, stream=False, **kwargs)
            
            # Send the request
            try:
                session = self.client.send_request(request=request, stream=False, **kwargs)
                print(f"Request sent. Received status code: {session.http_response.status_code}")
            except Exception as e:
                print(f"An error occurred while sending the request: {e}")
                raise

            # Check status code
            if session.http_response.status_code == 200:
                print("Handling 200 response...")
                return self.on_200(session)
            
            print("Handling error response...")
            return self.on_error(session.http_response)

        @property
        def url(self):
            # format_url uses management.azure.com and acquirePolicyToken isn't available :(
            url = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/providers/Microsoft.Authorization/acquirePolicyToken"
            return url

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"
        
        @property
        def content(self):
            operation_uri = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/resourceGroups/{self.ctx.args.resource_group}/providers/Microsoft.Cdn/profiles/{self.ctx.args.profile_name}?api-version=2025-04-15"

            content = {
                "operation": {
                    "uri": operation_uri,
                    "httpMethod": "DELETE"
                },
                "changeReference": f"/subscriptions/{self.ctx.subscription_id}/resourceGroups/{self.ctx.args.resource_group}/providers/Microsoft.ChangeSafety/changeStates/zhaocelinac2/stageProgressions/breakglassStage"
            }
            print(f"Content: {content}")
            return content
        
        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-03-01",
                    required=True,
                ),
            }
            return parameters
        
        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
            }
            return parameters
        
        def on_200(self, session):
            return self.deserialize_http_content(session)
        
        def on_204(self, session):
            pass

class _DeleteHelper:
    """Helper class for Delete"""


__all__ = ["Delete"]
