# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *

class AcquirePolicyToken(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"
        
        def __call__(self, *args, **kwargs):
            print("Making request...")
            request = self.make_request()
            print(f"Request made with URL: {request.url} and Method: {self.method}")
            session = self.client.send_request(request=request, stream=False, **kwargs)
            
            # Send the request
            try:
                session = self.client.send_request(request=request, stream=False, **kwargs)
                print(f"Request sent. Received status code: {session.http_response.status_code}")
            except Exception as e:
                print(f"An error occurred while sending the request: {e}")
                raise

            # Check status code
            if session.http_response.status_code == 200:
                print("Handling 200 response...")
                return self.on_200(session)
            
            print("Handling error response...")
            return self.on_error(session.http_response)

        @property
        def url(self):
            # format_url uses management.azure.com and acquirePolicyToken isn't available :(
            url = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/providers/Microsoft.Authorization/acquirePolicyToken"
            return url

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"
        
        @property
        def content(self):
            operation_uri = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/resourceGroups/{self.ctx.args.resource_group}/providers/Microsoft.Cdn/profiles/{self.ctx.args.profile_name}?api-version=2024-09-01"
            
            operation = {
                "uri": operation_uri,
                "httpMethod": str(self.ctx.args.http_method)
            }

            if self.ctx.args.http_method == "PUT":
                _content_value, _builder = self.new_content_builder(
                    self.ctx.args,
                    typ=AAZObjectType,
                    typ_kwargs={"flags": {"required": True, "client_flatten": True}}
                )
                _builder.set_prop("identity", AAZIdentityObjectType, ".identity")
                _builder.set_prop("location", AAZStrType, ".location", typ_kwargs={"flags": {"required": True}})
                _builder.set_prop("properties", AAZObjectType, typ_kwargs={"flags": {"client_flatten": True}})
                _builder.set_prop("sku", AAZObjectType, ".", typ_kwargs={"flags": {"required": True}})
                _builder.set_prop("tags", AAZDictType, ".tags")

                identity = _builder.get(".identity")
                if identity is not None:
                    identity.set_prop("type", AAZStrType, ".type", typ_kwargs={"flags": {"required": True}})
                    identity.set_prop("userAssignedIdentities", AAZDictType, ".user_assigned_identities")
                    identity.set_prop("userAssigned", AAZListType, ".mi_user_assigned", typ_kwargs={"flags": {"action": "create"}})
                    identity.set_prop("systemAssigned", AAZStrType, ".mi_system_assigned", typ_kwargs={"flags": {"action": "create"}})

                user_assigned_identities = _builder.get(".identity.userAssignedIdentities")
                if user_assigned_identities is not None:
                    user_assigned_identities.set_elements(AAZObjectType, ".")

                user_assigned = _builder.get(".identity.userAssigned")
                if user_assigned is not None:
                    user_assigned.set_elements(AAZStrType, ".")

                properties = _builder.get(".properties")
                if properties is not None:
                    properties.set_prop("logScrubbing", AAZObjectType, ".log_scrubbing")
                    properties.set_prop("originResponseTimeoutSeconds", AAZIntType, ".origin_response_timeout_seconds")

                log_scrubbing = _builder.get(".properties.logScrubbing")
                if log_scrubbing is not None:
                    log_scrubbing.set_prop("scrubbingRules", AAZListType, ".scrubbing_rules")
                    log_scrubbing.set_prop("state", AAZStrType, ".state")

                scrubbing_rules = _builder.get(".properties.logScrubbing.scrubbingRules")
                if scrubbing_rules is not None:
                    scrubbing_rules.set_elements(AAZObjectType, ".")

                _elements = _builder.get(".properties.logScrubbing.scrubbingRules[]")
                if _elements is not None:
                    _elements.set_prop("matchVariable", AAZStrType, ".match_variable", typ_kwargs={"flags": {"required": True}})
                    _elements.set_prop("selector", AAZStrType, ".selector")
                    _elements.set_prop("selectorMatchOperator", AAZStrType, ".selector_match_operator", typ_kwargs={"flags": {"required": True}})
                    _elements.set_prop("state", AAZStrType, ".state")

                sku = _builder.get(".sku")
                if sku is not None:
                    sku.set_prop("name", AAZStrType, ".sku")

                tags = _builder.get(".tags")
                if tags is not None:
                    tags.set_elements(AAZStrType, ".")
                
                content = self.serialize_content(_content_value)

                self.ctx.args.content = _content_value
                print(f"Token content: {content}, arg: {self.ctx.args.content}, {self.serialize_content(self.ctx.args.content)}, val: {_content_value}, {self.serialize_content(_content_value)}")

                operation["content"] = {
                    "properties": content
                }

            payload = {
                "operation": operation
            }
            
            if self.ctx.args.change_reference:
                payload["changeReference"] = str(self.ctx.args.change_reference)
            
            print(f"Resource payload: {payload}")
            return payload
        
        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-03-01",
                    required=True,
                ),
            }
            return parameters
        
        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
            }
            return parameters
        
        def on_200(self, session):
            return self.deserialize_http_content(session)
        
        def on_204(self, session):
            pass