# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *

class AcquirePolicyToken(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"
        
        def __call__(self, *args, **kwargs):
            print("Making request...")
            request = self.make_request()
            print(f"Request made with URL: {request.url} and Method: {self.method}")
            session = self.client.send_request(request=request, stream=False, **kwargs)
            
            # Send the request
            try:
                session = self.client.send_request(request=request, stream=False, **kwargs)
                print(f"Request sent. Received status code: {session.http_response.status_code}")
            except Exception as e:
                print(f"An error occurred while sending the request: {e}")
                raise

            # Check status code
            if session.http_response.status_code == 200:
                print("Handling 200 response...")
                return self.on_200(session)
            
            print("Handling error response...")
            return self.on_error(session.http_response)

        @property
        def url(self):
            # format_url uses management.azure.com and acquirePolicyToken isn't available :(
            url = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/providers/Microsoft.Authorization/acquirePolicyToken"
            return url

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"
        
        @property
        def content(self):
            operation_uri = f"https://eastus2euap.management.azure.com/subscriptions/{self.ctx.subscription_id}/resourceGroups/{self.ctx.args.resource_group}/providers/Microsoft.Cdn/profiles/{self.ctx.args.profile_name}?api-version=2024-09-01"
            
            operation = {
                "uri": operation_uri,
                "httpMethod": str(self.ctx.args.http_method)
            }

            if self.ctx.args.http_method == "PUT":
                operation["content"] = {
                    "properties": {
                        "location": "global",
                        "sku": {
                            "name": "Standard_AzureFrontDoor"
                        }
                    }
                }

            payload = {
                "operation": operation
            }
            
            if self.ctx.args.change_reference:
                payload["changeReference"] = str(self.ctx.args.change_reference)
            
            print(f"Resource payload: {payload}")
            return payload
        
        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-03-01",
                    required=True,
                ),
            }
            return parameters
        
        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
            }
            return parameters
        
        def on_200(self, session):
            return self.deserialize_http_content(session)
        
        def on_204(self, session):
            pass